name: wakatime-stats

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  update-readme:
    name: Update Wakatime Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE: "Update Wakatime Metrics"
          SHOW_DAYS_OF_WEEK: true
          SHOW_PROFILE_VIEWS: false
          SHOW_SHORT_INFO: false
          SHOW_TOTAL_CODE_TIME: false
          LOCALE: "en"
