name: wakatime-stats

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  update-readme:
    name: Update Wakatime Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN:     ${{ secrets.GH_TOKEN }}
          BRANCH:           "main"
          SHOW_COMMIT:       "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE:     "True"
          SHOW_OS:           "True"
